[package]
name = "hotwings-cli"
version = "0.1.0"
authors = ["Alex Yang <aleozlx@gmail.com>"]
edition = "2018"

[dependencies]
clap = "^2.32.0"
regex = "^1.1"
chrono = "^0.4.6"
yaml-rust = "^0.4"
colored = "1.6"
handlebars = "^1.1.0"
